<a href="https://colab.research.google.com/github/sunil1206/Data-science/blob/main/MUSHROOM_DATA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LOAD DATA

In [ ]:
import pandas as pd

df=pd.read_csv('/content/mushrooms.csv')
df

class cap-shape cap-surface  ... spore-print-color population habitat
0        p         x           s  ...                 k          s       u
1        e         x           s  ...                 n          n       g
2        e         b           s  ...                 n          n       m
3        p         x           y  ...                 k          s       u
4        e         x           s  ...                 n          a       g
...    ...       ...         ...  ...               ...        ...     ...
8119     e         k           s  ...                 b          c       l
8120     e         x           s  ...                 b          v       l
8121     e         f           s  ...                 b          c       l
8122     p         k           y  ...                 w          v       l
8123     e         x           s  ...                 o          c       l

[8124 rows x 23 columns]

BASIC INFORMATION

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [ ]:
df.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [ ]:
df.describe()

class cap-shape cap-surface  ... spore-print-color population habitat
count   8124      8124        8124  ...              8124       8124    8124
unique     2         6           4  ...                 9          6       7
top        e         x           y  ...                 w          v       d
freq    4208      3656        3244  ...              2388       4040    3148

[4 rows x 23 columns]

In [ ]:
df.shape

(8124, 23)

In [ ]:
x=df.drop(['class'],axis=1)
y=df['class']

In [ ]:
x.head()

cap-shape cap-surface cap-color  ... spore-print-color population habitat
0         x           s         n  ...                 k          s       u
1         x           s         y  ...                 n          n       g
2         b           s         w  ...                 n          n       m
3         x           y         w  ...                 k          s       u
4         x           s         g  ...                 n          a       g

[5 rows x 22 columns]

In [ ]:
x.nunique()

cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      2
odor                         9
gill-attachment              2
gill-spacing                 2
gill-size                    2
gill-color                  12
stalk-shape                  2
stalk-root                   5
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    1
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

In [ ]:
#Label encoding

from sklearn.preprocessing import LabelEncoder

le_x=LabelEncoder()

for i in x.columns:
  x[i]=le_x.fit_transform(x[i])
le_y=LabelEncoder()
y=le_y.fit_transform(y)

x.head()

cap-shape  cap-surface  cap-color  ...  spore-print-color  population  habitat
0          5            2          4  ...                  2           3        5
1          5            2          9  ...                  3           2        1
2          0            2          8  ...                  3           2        3
3          5            3          8  ...                  2           3        5
4          5            2          3  ...                  3           0        1

[5 rows x 22 columns]

In [ ]:
x=pd.get_dummies(x,columns=x.columns,drop_first=True)
x.head()

cap-shape_1  cap-shape_2  cap-shape_3  ...  habitat_4  habitat_5  habitat_6
0            0            0            0  ...          0          1          0
1            0            0            0  ...          0          0          0
2            0            0            0  ...          0          0          0
3            0            0            0  ...          0          1          0
4            0            0            0  ...          0          0          0

[5 rows x 95 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

**Feature** **Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train=sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

x_train = pca.fit_transform(x_train)
x_test = pca.fit_transform(x_test)

**GaussianNB**

In [ ]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_train,y_train)


GaussianNB()

In [ ]:
y_pred=gb.predict(x_test)

Making confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm=confusion_matrix(y_test,y_pred)
print('Accuracy score:', accuracy_score(y_test,y_pred))
cm

Accuracy score: 0.8978671041837571


array([[1210,   47],
       [ 202,  979]])

**HYPER TUNNING**

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV

parameters = {'var_smoothing': np.logspace(0,-9, num=100)}
Bayes = GridSearchCV(estimator=gb,
                     param_grid=parameters,
                     scoring='accuracy',
                     n_jobs=-1,
                     verbose=5,
                     cv=10)
Bayes.fit(x_train, y_train)
print('Train Accuracy : %.3f'%Bayes.best_estimator_.score(x_train, y_train))
print('Test Accuracy : %.3f'%Bayes.best_estimator_.score(x_test, y_test))
print('Best estimator : ',Bayes.best_estimator_)
print('Best Accuracy score:',Bayes.best_score_)
predictions = Bayes.best_estimator_.predict(x_test)
print('Accuracy score:', accuracy_score(y_test,predictions))
cm=confusion_matrix(y_test,predictions)
cm

Fitting 10 folds for each of 100 candidates, totalling 1000 fits
Train Accuracy : 0.898
Test Accuracy : 0.898
Best estimator :  GaussianNB(var_smoothing=0.003511191734215131)
Best Accuracy score: 0.8981716750414614
Accuracy score: 0.8982772764561116


array([[1212,   45],
       [ 203,  978]])

**FITTING BERNOULLINB**

In [ ]:
from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB()
bnb.fit(x_train,y_train)
y_pred=bnb.predict(x_test)

In [ ]:
cm=confusion_matrix(y_test,y_pred)
print('Accuracy score:', accuracy_score(y_test,y_pred))
cm

Accuracy score: 0.8900738310090238


array([[1235,   22],
       [ 246,  935]])

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV

parameters = {'alpha':[0.01, 0.1, 0.5, 1.0, 10.0]}
bnb_param = GridSearchCV(estimator=bnb,
                     param_grid=parameters,
                     scoring='accuracy',
                     n_jobs=-1,
                     verbose=5,
                     cv=10)
bnb_param.fit(x_train, y_train)
print('Train Accuracy : %.3f'%bnb_param.best_estimator_.score(x_train, y_train))
print('Test Accuracy : %.3f'%bnb_param.best_estimator_.score(x_test, y_test))
print(bnb_param.best_estimator_)
print('Best Accuracy score:',bnb_param.best_score_)
predictions = bnb_param.best_estimator_.predict(x_test)
print('Accuracy score:', accuracy_score(y_test,predictions))
cm=confusion_matrix(y_test,predictions)
cm

Fitting 10 folds for each of 5 candidates, totalling 50 fits
Train Accuracy : 0.888
Test Accuracy : 0.890
BernoulliNB(alpha=0.01)
Best Accuracy score: 0.8881469838362335
Accuracy score: 0.8900738310090238


array([[1235,   22],
       [ 246,  935]])

In [ ]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Instantiate dt
dt = DecisionTreeClassifier(min_samples_leaf=0.13, random_state=42)

# Instantiate LogisticRegression
lr = LogisticRegression(random_state=42)

# Instantiate random forest
rf = RandomForestClassifier( random_state = 42)

# Instantiate SVM
from sklearn.svm import SVC
svc = SVC(kernel='rbf',random_state=42)

# Instantiate KNN
from sklearn.neighbors import KNeighborsClassifier as KNN
knn = KNN(n_neighbors=7)


In [ ]:
# Define the list classifiers
classifiers = [ ('K Nearest Neighbours', knn), ('Classification Tree', dt), ('BernoulliNB',bnb_param),('GaussianNB',Bayes),('Random Forest',rf),('SVC',svc),('Logistic regresion',lr)]

from sklearn.metrics import accuracy_score,roc_auc_score
for clf_name,clf in classifiers:
    clf.fit(x_train,y_train)
    y_pred=clf.predict(x_test)

    accuracy=accuracy_score(y_test,y_pred)

    print('{:s} : {:.4f}'.format(clf_name, accuracy))

K Nearest Neighbours : 0.9130
Classification Tree : 0.8979
Fitting 10 folds for each of 5 candidates, totalling 50 fits
BernoulliNB : 0.8901
Fitting 10 folds for each of 100 candidates, totalling 1000 fits
GaussianNB : 0.8983
Random Forest : 0.9102
SVC : 0.9024
Logistic regresion : 0.9024


In [ ]:

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

knn = KNN()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print('Accuracy score:', accuracy_score(y_test,y_pred))
parameters={'metric':['minkowski','euclidean','manhattan'],
            'n_neighbors':[1,2,3,4,5,6,8,9,10,11,12,13,14,15],
            'weights':['uniform','distance']}
knn_param = GridSearchCV(estimator=knn,
                     param_grid=parameters,
                     scoring='accuracy',
                     n_jobs=-1,
                     verbose=5,
                     cv=10)
knn_param.fit(x_train, y_train)
predictions = knn_param.best_estimator_.predict(x_test)
print('Best parameters:',knn_param.best_params_)
print(knn_param.best_estimator_)
print('Train Accuracy : %.3f'%knn_param.best_estimator_.score(x_train, y_train))
print('Test Accuracy : %.3f'%knn_param.best_estimator_.score(x_test, y_test))
print('Best Accuracy score:',knn_param.best_score_)
print('Accuracy score:', accuracy_score(y_test,predictions))

print(confusion_matrix(y_test,predictions ))

from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

Accuracy score: 0.9109926168990976
Fitting 10 folds for each of 84 candidates, totalling 840 fits
Best parameters: {'metric': 'manhattan', 'n_neighbors': 15, 'weights': 'uniform'}
KNeighborsClassifier(metric='manhattan', n_neighbors=15)
Train Accuracy : 0.939
Test Accuracy : 0.919
Best Accuracy score: 0.9358071981979752
Accuracy score: 0.918785890073831
[[1205   52]
 [ 146 1035]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92      1257
           1       0.95      0.88      0.91      1181

    accuracy                           0.92      2438
   macro avg       0.92      0.92      0.92      2438
weighted avg       0.92      0.92      0.92      2438



In [ ]:
accuracy=accuracy_score(y_test,predictions)
accuracy

0.918785890073831